// JoqniX Cookie Sync
// Background Service Worker
// Version: 0.2.0

const SUPPORTED_DOMAINS = [
  "youtube.com",
  "twitch.tv",
  "kick.com"
];

/**
 * Check whether a cookie belongs to one of our supported domains.
 */
function isSupportedCookie(cookie) {
  const domain = cookie.domain.replace(/^\./, "").toLowerCase();

  return SUPPORTED_DOMAINS.some(
    supportedDomain =>
      domain === supportedDomain ||
      domain.endsWith(`.${supportedDomain}`)
  );
}

/**
 * Determine which supported service a cookie belongs to.
 */
function getCookieService(cookie) {
  const domain = cookie.domain
    .replace(/^\./, "")
    .toLowerCase();

  return SUPPORTED_DOMAINS.find(
    supportedDomain =>
      domain === supportedDomain ||
      domain.endsWith(`.${supportedDomain}`)
  ) || null;
}

/**
 * Get every cookie accessible to the extension,
 * then keep only cookies belonging to our supported domains.
 *
 * We intentionally retrieve the complete cookie jar here
 * because the goal is to reproduce the full Netscape
 * cookie export for each supported service.
 */
async function getSupportedCookies() {
  try {
    const cookies = await chrome.cookies.getAll({});

    return cookies.filter(isSupportedCookie);
  } catch (error) {
    console.error(
      "[Cookie Sync] Failed to read browser cookies:",
      error
    );

    throw error;
  }
}

/**
 * Create a safe structured representation of a Chrome cookie.
 *
 * This is kept for compatibility with popup.js and for
 * debugging. The Netscape representation is generated separately.
 */
function serializeCookie(cookie) {
  return {
    name: cookie.name,
    value: cookie.value,
    domain: cookie.domain,
    path: cookie.path,
    secure: cookie.secure,
    httpOnly: cookie.httpOnly,
    sameSite: cookie.sameSite,
    expirationDate: cookie.expirationDate ?? null,
    session: cookie.session
  };
}

/**
 * Convert one Chrome cookie into Netscape HTTP Cookie format.
 *
 * Netscape format:
 *
 * domain
 * includeSubdomains
 * path
 * secure
 * expiration
 * name
 * value
 *
 * HttpOnly cookies use:
 *
 * #HttpOnly_<domain>
 */
function cookieToNetscape(cookie) {
  let domain = cookie.domain;

  /**
   * Netscape cookie files represent HttpOnly cookies
   * by adding #HttpOnly_ before the domain.
   */
  if (cookie.httpOnly) {
    domain = `#HttpOnly_${domain}`;
  }

  /**
   * The Netscape domain flag indicates whether the cookie
   * applies to subdomains.
   *
   * Chrome preserves this through the leading dot on
   * domain cookies.
   */
  const includeSubdomains = cookie.domain.startsWith(".")
    ? "TRUE"
    : "FALSE";

  const path = cookie.path || "/";

  const secure = cookie.secure
    ? "TRUE"
    : "FALSE";

  /**
   * Session cookies have no expiration timestamp.
   *
   * Netscape cookie files use 0 for these.
   */
  const expiration = cookie.session
    ? "0"
    : Math.floor(cookie.expirationDate || 0);

  const name = cookie.name || "";
  const value = cookie.value || "";

  return [
    domain,
    includeSubdomains,
    path,
    secure,
    expiration,
    name,
    value
  ].join("\t");
}

/**
 * Convert cookies into a complete Netscape Cookie File.
 */
function cookiesToNetscape(cookies, domainName) {
  const header = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by JoqniX Cookie Sync",
    `# Domain: ${domainName}`,
    ""
  ].join("\n");

  /**
   * Sort cookies for stable output.
   *
   * This makes comparing old and new exports much easier.
   */
  const sortedCookies = [...cookies].sort((a, b) => {
    const domainCompare =
      a.domain.localeCompare(b.domain);

    if (domainCompare !== 0) {
      return domainCompare;
    }

    const pathCompare =
      a.path.localeCompare(b.path);

    if (pathCompare !== 0) {
      return pathCompare;
    }

    return a.name.localeCompare(b.name);
  });

  const lines = sortedCookies.map(cookieToNetscape);

  return `${header}\n${lines.join("\n")}\n`;
}

/**
 * Generate Netscape Cookie Files for every supported service.
 */
function generateNetscapeFiles(cookies) {
  const files = {};

  for (const domain of SUPPORTED_DOMAINS) {
    const domainCookies = cookies.filter(
      cookie =>
        getCookieService(cookie) === domain
    );

    files[domain] = cookiesToNetscape(
      domainCookies,
      domain
    );
  }

  return files;
}

/**
 * Save the complete cookie snapshot and Netscape exports
 * locally using chrome.storage.local.
 */
async function saveCookieSnapshot() {
  try {
    const cookies = await getSupportedCookies();

    const snapshot = cookies.map(serializeCookie);

    const netscapeFiles =
      generateNetscapeFiles(cookies);

    const cookieCounts = {};

    for (const domain of SUPPORTED_DOMAINS) {
      cookieCounts[domain] = cookies.filter(
        cookie =>
          getCookieService(cookie) === domain
      ).length;
    }

    const timestamp = Date.now();

    await chrome.storage.local.set({
      cookieSnapshot: snapshot,
      netscapeFiles,
      cookieCounts,
      lastLocalSync: timestamp
    });

    console.log(
      `[Cookie Sync] Local snapshot updated: ${snapshot.length} cookies`
    );

    console.log(
      "[Cookie Sync] Cookie counts:",
      cookieCounts
    );

    return {
      cookies,
      snapshot,
      netscapeFiles,
      cookieCounts,
      timestamp
    };

  } catch (error) {
    console.error(
      "[Cookie Sync] Failed to save cookie snapshot:",
      error
    );

    throw error;
  }
}

/**
 * Handle cookie changes.
 *
 * Any relevant cookie change causes the complete local
 * Netscape snapshots to be rebuilt.
 */
chrome.cookies.onChanged.addListener(async changeInfo => {
  const cookie = changeInfo.cookie;

  if (!isSupportedCookie(cookie)) {
    return;
  }

  console.log("[Cookie Sync] Cookie changed:", {
    cause: changeInfo.cause,
    removed: changeInfo.removed,
    name: cookie.name,
    domain: cookie.domain,
    path: cookie.path
  });

  try {
    await saveCookieSnapshot();
  } catch (error) {
    console.error(
      "[Cookie Sync] Failed to update after cookie change:",
      error
    );
  }
});

/**
 * Messages from popup.js or other extension pages.
 */
chrome.runtime.onMessage.addListener(
  (message, sender, sendResponse) => {

    if (
      !message ||
      typeof message.type !== "string"
    ) {
      return;
    }

    /**
     * Return all structured cookies.
     *
     * Existing popup.js uses this.
     */
    if (message.type === "GET_COOKIES") {
      getSupportedCookies()
        .then(cookies => {
          sendResponse({
            success: true,
            cookies: cookies.map(serializeCookie)
          });
        })
        .catch(error => {
          sendResponse({
            success: false,
            error: error.message
          });
        });

      return true;
    }

    /**
     * Rebuild the complete local snapshot.
     */
    if (message.type === "SYNC_LOCAL") {
      saveCookieSnapshot()
        .then(result => {
          sendResponse({
            success: true,
            count: result.snapshot.length,
            cookieCounts: result.cookieCounts,
            timestamp: result.timestamp
          });
        })
        .catch(error => {
          sendResponse({
            success: false,
            error: error.message
          });
        });

      return true;
    }

    /**
     * Return current extension status.
     */
    if (message.type === "GET_STATUS") {
      chrome.storage.local
        .get([
          "cookieSnapshot",
          "cookieCounts",
          "lastLocalSync"
        ])
        .then(data => {
          sendResponse({
            success: true,
            cookieCount:
              data.cookieSnapshot?.length ?? 0,

            cookieCounts:
              data.cookieCounts ?? {},

            lastLocalSync:
              data.lastLocalSync ?? null
          });
        })
        .catch(error => {
          sendResponse({
            success: false,
            error: error.message
          });
        });

      return true;
    }

    /**
     * Return the generated Netscape Cookie Files.
     */
    if (message.type === "GET_NETSCAPE") {
      chrome.storage.local
        .get([
          "netscapeFiles",
          "lastLocalSync"
        ])
        .then(async data => {

          /**
           * If no Netscape snapshot exists yet,
           * generate one immediately.
           */
          if (!data.netscapeFiles) {
            const result =
              await saveCookieSnapshot();

            sendResponse({
              success: true,
              files: result.netscapeFiles,
              timestamp: result.timestamp
            });

            return;
          }

          sendResponse({
            success: true,
            files: data.netscapeFiles,
            timestamp:
              data.lastLocalSync ?? null
          });
        })
        .catch(error => {
          sendResponse({
            success: false,
            error: error.message
          });
        });

      return true;
    }

    /**
     * Return the complete current Netscape exports
     * directly from the browser cookie store.
     */
    if (message.type === "EXPORT_NETSCAPE") {
      getSupportedCookies()
        .then(cookies => {
          const files =
            generateNetscapeFiles(cookies);

          sendResponse({
            success: true,
            files,
            cookieCount: cookies.length
          });
        })
        .catch(error => {
          sendResponse({
            success: false,
            error: error.message
          });
        });

      return true;
    }
  }
);

/**
 * Initialize the local snapshot when the extension starts.
 */
chrome.runtime.onStartup.addListener(async () => {
  console.log(
    "[Cookie Sync] Extension startup"
  );

  try {
    await saveCookieSnapshot();
  } catch (error) {
    console.error(
      "[Cookie Sync] Startup sync failed:",
      error
    );
  }
});

/**
 * Initialize when the extension is installed or updated.
 */
chrome.runtime.onInstalled.addListener(
  async details => {

    console.log(
      `[Cookie Sync] Extension ${details.reason}`
    );

    try {
      await saveCookieSnapshot();
    } catch (error) {
      console.error(
        "[Cookie Sync] Installation sync failed:",
        error
      );
    }
  }
);

console.log(
  "[Cookie Sync] Background service worker loaded."
);
